name: nf-itdepends CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build nf-itdepends
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java_version: [17, 21]
        nextflow_version: ['24.04.0', '24.10', '25.04']

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Java ${{ matrix.java_version }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3

      - name: Build plugin
        run: make assemble

      - name: Run tests
        run: make test

      - name: Install plugin locally
        run: make install

      - name: Setup Nextflow ${{ matrix.nextflow_version }}
        uses: nf-core/setup-nextflow@b9f764e8ba5c76b712ace14ecbfcef0e40ae2dd8 # v1
        with:
          version: "${{ matrix.nextflow_version }}"

      - name: Get plugin version
        id: version
        run: echo "version=$(grep '^version' build.gradle | sed "s/version = '//;s/'//")" >> "$GITHUB_OUTPUT"

      - name: Run validation pipeline
        run: nextflow run validation/ -plugins nf-itdepends@${{ steps.version.outputs.version }}

      - name: Upload plugin artifact
        if: matrix.java_version == 21 && matrix.nextflow_version == '25.04'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: nf-itdepends-plugin
          path: build/distributions/*.zip
